#!/usr/bin/env node
/**
 * Writes .env.local for zero-config Ollama (no API keys from the internet).
 */
import { writeFileSync, existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = resolve(root, '.env.local');
const ollamaOrigin = 'http://127.0.0.1:11434';

const PREFERRED = [
  'nemotron-3-ultra:cloud',
  'nemotron-3-super',
  'llama3.3',
  'llama3.2',
  'qwen2.5-coder',
];

async function detect() {
  try {
    const res = await fetch(`${ollamaOrigin}/api/tags`, { signal: AbortSignal.timeout(3000) });

    if (!res.ok) {
      return null;
    }

    const data = await res.json();
    const names = (data.models ?? []).map((m) => m.name).filter(Boolean);

    if (!names.length) {
      return null;
    }

    for (const id of PREFERRED) {
      const hit = names.find((n) => n.toLowerCase() === id.toLowerCase());

      if (hit) {
        return hit;
      }
    }

    return names[0];
  } catch {
    return null;
  }
}

function mergeEnv(existing, lines) {
  const map = new Map();

  for (const line of existing.split('\n')) {
    if (!line.trim() || line.trim().startsWith('#')) {
      continue;
    }

    const idx = line.indexOf('=');

    if (idx > 0) {
      map.set(line.slice(0, idx).trim(), line.slice(idx + 1).trim());
    }
  }

  for (const line of lines) {
    const idx = line.indexOf('=');

    if (idx > 0) {
      map.set(line.slice(0, idx).trim(), line.slice(idx + 1).trim());
    }
  }

  return [
    '# Everix AI — generated by npm run setup:llm',
    '# Leave LLM_PROVIDER unset to auto-detect Ollama or env API keys.',
    '',
    ...Object.entries(map).map(([k, v]) => `${k}=${v}`),
    '',
  ].join('\n');
}

const model = await detect();

if (!model) {
  console.log(`
Could not find Ollama on ${ollamaOrigin}.

1. Install: https://ollama.com/download
2. Sign in (for cloud models): ollama signin
3. Pull/run a model, e.g.:
   ollama run nemotron-3-ultra:cloud
4. Run this script again: npm run setup:llm

Optional free cloud keys (copy .env.example) — we do NOT download keys from GitHub.
`);
  process.exit(1);
}

const newLines = [
  `LLM_PROVIDER=ollama`,
  `LLM_MODEL=${model}`,
  `OLLAMA_BASE_URL=http://127.0.0.1:11434/v1`,
];

const existing = existsSync(envPath) ? readFileSync(envPath, 'utf8') : '';
const content = mergeEnv(existing, newLines);

writeFileSync(envPath, content, 'utf8');

console.log(`Wrote ${envPath}`);
console.log(`Using Ollama model: ${model}`);
console.log('Restart: npm run dev');
